# Generated by Django 2.2 on 2019-04-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190421_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtown',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
