# Generated by Django 2.2 on 2019-04-29 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0003_downtown_bio'), ('main', '0004_auto_20190429_0123'), ('main', '0005_auto_20190429_0134')]

    dependencies = [
        ('main', '0002_auto_20190421_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtown',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='attending',
            field=models.ManyToManyField(to='main.Downtown'),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
