# Generated by Django 2.2 on 2019-05-03 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190429_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attending',
            field=models.ManyToManyField(blank=True, to='main.Downtown'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
