# Generated by Django 2.2 on 2019-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190503_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
