# Generated by Django 2.2 on 2019-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190505_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
