# Generated by Django 2.2 on 2019-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticket_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
